# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: AlizÃ©e Bardon
title: Bioinformatician
email: alizee.bardon@ifremer.fr
#website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
#twitter_username: facespics
github_username:  AlizeeBardon
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: AlizÃ©e Bardon
linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content:  # this will include new lines to allow paragraphs:w
  I am a master student in Bioinformatics from the University of Rouen (France), and I am an apprentice at Ifremer (France).
  This formation gave me the opportunity to work on different aspects of computational biology, like programming (bash, python), statistics (R),
  web development (Django, RShiny), databases (SQL, NoSQL).
  During my apprenticeship at Ifremer, I have worked on many aspects of bioinformatic web development and omics data management.
  Passionate about nature and ecology, I also hold a Master of Systematic, Evolution and Paleontology,
  from the Museum National dâ€™Histoire Naturelle, Paris,France. 
 
 
  Eager to take on new challenges, I am looking for a new experience starting in february 2023 that would combines the fields I love; ecology and bioinformatics \


  <b>Skills</b> 

  <mark>Bioinformatic</mark> - <mark>Web Development</mark> - <mark>Marine Biology</mark> <mark>Ecology</mark> <mark>Evolution</mark>

content:


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
    
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: Master of Bioinformatic Modelisation et Statistic 
        caption: 2021-2023
        sub_title: University of Rouen (France)
        link: http://masterbioinfo.univ-rouen.fr/
        link_text: BIMS
        description: | # this will include new lines to allow paragraphs
          DApprentiship at Ifremer (Brest) during 1.5 years.
    
    
      - layout: top
        title: Master of Bioinformatic Modelisation et Statistic 
        caption: 2021-2023
        sub_title: University of Rouen (France)
        link: http://masterbioinfo.univ-rouen.fr/
        link_text: BIMS 
        description: | # this will include new lines to allow paragraphs
          Apprentiship at Ifremer (Brest) during 1.5 years.

      - layout: left
        title: Master of Systematic, Evolution and Paleontology
        caption: 2018-2020
        sub_title: MusÃ©um National dâ€™Histoire Naturelle, Paris (France)
        quote: >
          Best formation ever : field,  internship
        description: | # this will include new lines to allow paragraphs
          Specialization Biodiversityâ€™s History, Paleontology, & Computer Science Applied to Biodiversity
          
          
      - layout: left
        title: Bachelor of Biology and Geology
        caption: 2002 â€“ 2003
        sub_title: Cergy-Pontoise University (France)


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: SeBiMER | Ifremer  
        link: https://wwz.ifremer.fr/Recherche/Departements-scientifiques/Departement-Infrastructures-de-Recherche-et-Systemes-d-Information/Bioinformatique
        link_text: SeBiMER
        sub_title: Apprenticeship, Genome Browser Project, Ifremer
        caption: September 2021 - January 2023
        quote: >
          *Highlighting Ifremer model organisms through genomic data visualisation*
        description: | # this will include new lines to allow paragraphs
            Supervisor: LEROI L.
            - Setting up a genomic visualisation platform to gather the omics data of Ifremer model organisms. 
            - Implementing JBrowse2 to Galaxy Ifremer in order facilitate the omics data visualisation. 




  - title: Bioinformatic Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Ifremer Genomes Catalog
        link: https://genomes-catalog.ifremer.fr/
        link_text: genomes-catalog
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Find here genomes and omics data for marine organisms studied at Ifremer! ðŸŸ
          
        description: | # this will include new lines to allow paragraphs
          Ifremer's Genome Catalog platform provides access to the omics resources ðŸ§¬ of model marine organisms studied at Ifremer. \
          Genomes Catalog is an interactive web application that organizes entries through their metadata (taxonomy, assembly quality) and 
          give access to a Genome Browser [JBrowse2](https://jbrowse.org/jb2/) to visualise the omics data of each species. \
          The new data addition is automated thanks to the [omics-catalog workflow](https://github.com/ifremer-bioinformatics/omics-catalog). \
          My work was the enhence the original pipeline with new features (adding multiple tracks, data management, verification steps). 
          In addition to the public catalog, I have set up a private instance for viewing unpublished data on which teams are collaborating.
          
      - layout: top
        title: Differential expression Analysis in ShinY for RNA seq
        link: https://github.com/AlizeeBardon/shiny_enrichment_analysis
        link_text: DAISY
        #additional_links:
          #- title:  sproogen/modern-resume-theme
          #  icon: fab fa-github
          #  url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This interactive Shiny application aims to facilitate and automate the analysis of functional enrichment analysis
          
        description: | # this will include new lines to allow paragraphs
          * Web application  RShiny
          * Project management GitHub
          * RNAseq Funtional enrichment analysis
          \\
          Context
          Course of Bioinformatics in Omics Sciences NGS sequencing data analysis and annotation S3-UE5 
          Master of BioInformatics Modeling and Statistics, University of Rouen
          2020
          
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
